call plug#begin('~/.vim/plugged')
call plug#end() 
syntax on
colorscheme onedark 
set autoindent
"set spell spelllang=en_us
set tabstop=4
set shiftwidth=4
"set expandtab
"set smarttab
set incsearch
set ai
set number
"set relativenumber
set hlsearch
set ruler
filetype plugin on
set omnifunc=syntaxcomplete#Complete
"colorscheme DimBlue
"colorscheme wombat256grf
"highlight Comment ctermfg=green
