"coloring
syntax on
set background=dark
colorscheme toast 
highlight Comment ctermfg=green
"formatting
set expandtab
set tabstop=2
set shiftwidth=2
set autoindent
set smartindent
"search
set hlsearch
set incsearch
"navigation info
set number
set relativenumber
set ruler

